Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = []
src += Glob('*.c')
CPPPATH = [cwd]

group = DefineGroup('test_cir', src, depend = ['APP_USE_CIR_TEST'], CPPPATH = CPPPATH)

Return('group')