# RT-Thread building script for component

Import('AIC_ROOT')
Import('PRJ_KERNEL')
Import('rtconfig')
from building import *
import os

cwd     = GetCurrentDir()
src   = []
group   = []

CPPPATH = [cwd]
prj_chip = GetDepend('PRJ_CHIP').strip('"')

src     = Glob('*.c')


group = DefineGroup('D12X_SECURE_BOOT', src, depend = ['AIC_CHIP_D12X', 'LPKG_USING_MARC_CHACHA20'], CPPPATH = CPPPATH, LIBS = [], LIBPATH = [])

Return('group')
