/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by UIBuilder
 * UIBuilder version: v2.1.1
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"

#include "lv_aic_player.h"

void __attribute__((weak)) scr_video_video_player_custom_clicked(void) {
}

static void scr_video_video_player_clicked (lv_event_t *e) {
    scr_video_video_player_custom_clicked();
}

void __attribute__((weak)) scr_video_next_custom_clicked(void) {
}

static void scr_video_next_clicked (lv_event_t *e) {
    scr_video_next_custom_clicked();
}

void __attribute__((weak)) scr_video_last_custom_clicked(void) {
}

static void scr_video_last_clicked (lv_event_t *e) {
    scr_video_last_custom_clicked();
}

void __attribute__((weak)) scr_video_zoom_custom_clicked(void) {
}

static void scr_video_zoom_clicked (lv_event_t *e) {
    scr_video_zoom_custom_clicked();
}

void __attribute__((weak)) scr_video_play_control_custom_clicked(void) {
}

static void scr_video_play_control_clicked (lv_event_t *e) {
    scr_video_play_control_custom_clicked();
}

static void scr_video_back_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // delete child obj of act_scr
        lv_obj_clean(act_scr);
        // create scr_home
        scr_home_create(&ui_manager);
        // load scr_home
        lv_scr_load_anim(scr_home_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_NONE, 0, 0, ui_manager.auto_del);
    }
}


void scr_video_create(ui_manager_t *ui)
{
    scr_video_t *scr = scr_video_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->video_player
    scr->video_player = lv_aic_player_create(scr->obj);
    lv_aic_player_set_src(scr->video_player, LVGL_VIDEO_PATH(What A Cute Black Cat.mp4));
    lv_aic_player_set_auto_restart(scr->video_player, true);
    lv_aic_player_set_cmd(scr->video_player, LV_AIC_PLAYER_CMD_START, NULL);
    lv_obj_set_pos(scr->video_player, 0, 0);
    lv_obj_set_size(scr->video_player, 1024, 600);
    lv_obj_add_flag(scr->video_player, LV_OBJ_FLAG_CLICKABLE);

    // Set event handler of scr->video_player
    lv_obj_add_event_cb(scr->video_player, scr_video_video_player_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->control_bar
    scr->control_bar = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->control_bar, 303, 530);
    lv_obj_set_size(scr->control_bar, 418, 60);
    lv_obj_set_scrollbar_mode(scr->control_bar, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->control_bar
    lv_obj_set_style_bg_opa(scr->control_bar, 124, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->control_bar, lv_color_hex(0x202020), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->control_bar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->control_bar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->control_bar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->control_bar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->control_bar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(scr->control_bar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->next
    scr->next = lv_imgbtn_create(scr->control_bar);
    lv_imgbtn_set_src(scr->next, LV_IMGBTN_STATE_RELEASED, NULL, LVGL_IMAGE_PATH(video/next.png), NULL);
    lv_imgbtn_set_src(scr->next, LV_IMGBTN_STATE_PRESSED, NULL, LVGL_IMAGE_PATH(video/next_press.png), NULL);
    lv_obj_t *scr_video_next_label = lv_label_create(scr->next);
    lv_label_set_text(scr_video_next_label, "");
    lv_obj_align(scr_video_next_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->next, 325, 5);
    lv_obj_set_size(scr->next, 50, 50);

    // Set style of scr->next
    lv_obj_set_style_text_font(scr->next, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->next
    lv_obj_add_event_cb(scr->next, scr_video_next_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->last
    scr->last = lv_imgbtn_create(scr->control_bar);
    lv_imgbtn_set_src(scr->last, LV_IMGBTN_STATE_RELEASED, NULL, LVGL_IMAGE_PATH(video/last.png), NULL);
    lv_imgbtn_set_src(scr->last, LV_IMGBTN_STATE_PRESSED, NULL, LVGL_IMAGE_PATH(video/last_press.png), NULL);
    lv_obj_t *scr_video_last_label = lv_label_create(scr->last);
    lv_label_set_text(scr_video_last_label, "");
    lv_obj_align(scr_video_last_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->last, 125, 5);
    lv_obj_set_size(scr->last, 50, 50);

    // Set style of scr->last
    lv_obj_set_style_text_font(scr->last, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->last
    lv_obj_add_event_cb(scr->last, scr_video_last_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->zoom
    scr->zoom = lv_img_create(scr->control_bar);
    lv_img_set_src(scr->zoom, LVGL_IMAGE_PATH(video/zoom_out.png));
    lv_img_set_pivot(scr->zoom, 50, 50);
    lv_img_set_offset_x(scr->zoom, 0);
    lv_img_set_offset_y(scr->zoom, 0);
    lv_img_set_angle(scr->zoom, 0);
    lv_obj_set_pos(scr->zoom, 25, 5);
    lv_obj_add_flag(scr->zoom, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->zoom
    lv_obj_set_style_img_recolor(scr->zoom, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->zoom
    lv_obj_add_event_cb(scr->zoom, scr_video_zoom_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->play_control
    scr->play_control = lv_img_create(scr->control_bar);
    lv_img_set_src(scr->play_control, LVGL_IMAGE_PATH(video/pause.png));
    lv_img_set_pivot(scr->play_control, 50, 50);
    lv_img_set_offset_x(scr->play_control, 0);
    lv_img_set_offset_y(scr->play_control, 0);
    lv_img_set_angle(scr->play_control, 0);
    lv_obj_set_pos(scr->play_control, 225, 5);
    lv_obj_add_flag(scr->play_control, LV_OBJ_FLAG_CLICKABLE);

    // Set event handler of scr->play_control
    lv_obj_add_event_cb(scr->play_control, scr_video_play_control_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->author
    scr->author = lv_label_create(scr->obj);
    lv_label_set_text(scr->author, "Author");
    lv_label_set_long_mode(scr->author, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->author, 100, 100);
    lv_obj_set_size(scr->author, 300, 32);

    // Set style of scr->author
    lv_obj_set_style_text_color(scr->author, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->author, fs_montserratmedium_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->file_name
    scr->file_name = lv_label_create(scr->obj);
    lv_label_set_text(scr->file_name, "File Name");
    lv_label_set_long_mode(scr->file_name, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->file_name, 100, 30);
    lv_obj_set_size(scr->file_name, 300, 32);

    // Set style of scr->file_name
    lv_obj_set_style_bg_image_opa(scr->file_name, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->file_name, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->file_name, fs_montserratmedium_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->back
    scr->back = lv_img_create(scr->obj);
    lv_img_set_src(scr->back, LVGL_IMAGE_PATH(home/back_solid_60x60.png));
    lv_img_set_pivot(scr->back, 50, 50);
    lv_img_set_offset_x(scr->back, 0);
    lv_img_set_offset_y(scr->back, 0);
    lv_img_set_angle(scr->back, 0);
    lv_obj_set_pos(scr->back, 0, 0);
    lv_obj_add_flag(scr->back, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->back
    lv_obj_set_style_img_recolor(scr->back, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(scr->back, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->back
    lv_obj_add_event_cb(scr->back, scr_video_back_clicked, LV_EVENT_CLICKED, NULL);


}


