/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by UIBuilder
 * UIBuilder version: v2.1.1
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"

#include "lv_aic_player.h"


void scr_setting_create(ui_manager_t *ui)
{
    scr_setting_t *scr = scr_setting_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->container
    scr->container = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->container, 0, 0);
    lv_obj_set_size(scr->container, 1024, 600);
    lv_obj_set_scrollbar_mode(scr->container, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->container
    lv_obj_set_style_bg_color(scr->container, lv_color_hex(0x646464), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->menu
    scr->menu = lv_menu_create(scr->container);
    lv_obj_t *scr_setting_menu_sidebar = lv_menu_page_create(scr->menu, NULL);
    lv_menu_set_sidebar_page(scr->menu, scr_setting_menu_sidebar);
    lv_obj_t *scr_setting_menu_sidebar_header = lv_menu_get_sidebar_header(scr->menu);
    lv_obj_add_flag(scr_setting_menu_sidebar_header, LV_OBJ_FLAG_HIDDEN);
    lv_obj_t *menu_main_header = lv_menu_get_main_header(scr->menu);
    lv_obj_add_flag(menu_main_header, LV_OBJ_FLAG_HIDDEN);

    lv_obj_t *scr_setting_menu_page_1 = lv_menu_page_create(scr->menu, NULL);
    lv_obj_t *scr_setting_menu_cont_1 = lv_menu_cont_create(scr_setting_menu_sidebar);
    lv_obj_set_style_border_side(scr_setting_menu_cont_1, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_t *scr_setting_menu_cont_1_lab = lv_label_create(scr_setting_menu_cont_1);
    lv_label_set_text(scr_setting_menu_cont_1_lab, "menu");
    lv_menu_set_load_page_event(scr->menu, scr_setting_menu_cont_1, scr_setting_menu_page_1);

    lv_obj_t *scr_setting_menu_page_2 = lv_menu_page_create(scr->menu, NULL);
    lv_obj_t *scr_setting_menu_cont_2 = lv_menu_cont_create(scr_setting_menu_sidebar);
    lv_obj_set_style_border_side(scr_setting_menu_cont_2, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_t *scr_setting_menu_cont_2_lab = lv_label_create(scr_setting_menu_cont_2);
    lv_label_set_text(scr_setting_menu_cont_2_lab, "menu");
    lv_menu_set_load_page_event(scr->menu, scr_setting_menu_cont_2, scr_setting_menu_page_2);

    lv_obj_t *scr_setting_menu_page_3 = lv_menu_page_create(scr->menu, NULL);
    lv_obj_t *scr_setting_menu_cont_3 = lv_menu_cont_create(scr_setting_menu_sidebar);
    lv_obj_set_style_border_side(scr_setting_menu_cont_3, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_t *scr_setting_menu_cont_3_lab = lv_label_create(scr_setting_menu_cont_3);
    lv_label_set_text(scr_setting_menu_cont_3_lab, "menu");
    lv_menu_set_load_page_event(scr->menu, scr_setting_menu_cont_3, scr_setting_menu_page_3);

#if LVGL_VERSION_MAJOR == 8
    lv_event_send(scr_setting_menu_cont_1, LV_EVENT_CLICKED, NULL);
#else
    lv_obj_send_event(scr_setting_menu_cont_1, LV_EVENT_CLICKED, NULL);
#endif
    lv_obj_set_pos(scr->menu, 0, 0);
    lv_obj_set_size(scr->menu, 1024, 600);

    // Set style of scr->menu
    lv_obj_set_style_border_opa(scr_setting_menu_cont_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr_setting_menu_cont_1, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(scr_setting_menu_cont_1, 0, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(scr_setting_menu_cont_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr_setting_menu_cont_2, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(scr_setting_menu_cont_2, 0, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(scr_setting_menu_cont_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr_setting_menu_cont_3, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(scr_setting_menu_cont_3, 0, LV_PART_MAIN | LV_STATE_CHECKED);

    // Init scr->container_1
    scr->container_1 = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->container_1, -577, 283);
    lv_obj_set_size(scr->container_1, 300, 200);
    lv_obj_set_scrollbar_mode(scr->container_1, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->container_1
    lv_obj_set_style_bg_color(scr->container_1, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->container_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);


}


