/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by UIBuilder
 * UIBuilder version: v2.1.1
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"

#include "lv_aic_player.h"

static void scr_about_back_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // delete child obj of act_scr
        lv_obj_clean(act_scr);
        // create scr_home
        scr_home_create(&ui_manager);
        // load scr_home
        lv_scr_load_anim(scr_home_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_NONE, 0, 0, ui_manager.auto_del);
    }
}


void scr_about_create(ui_manager_t *ui)
{
    scr_about_t *scr = scr_about_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xfcfcfc), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->qrcode_1
#if LVGL_VERSION_MAJOR == 8
    scr->qrcode_1 = lv_qrcode_create(scr->obj, 200, lv_color_hex(0x000000), lv_color_hex(0xffffff));
#else
    scr->qrcode_1 = lv_qrcode_create(scr->obj);
    lv_qrcode_set_size(scr->qrcode_1, 200);
    lv_qrcode_set_dark_color(scr->qrcode_1, lv_color_hex(0x000000));
    lv_qrcode_set_light_color(scr->qrcode_1, lv_color_hex(0xffffff));
#endif
    lv_qrcode_update(scr->qrcode_1, "https://www.display-lcd.com", strlen("https://www.display-lcd.com"));
    lv_obj_set_pos(scr->qrcode_1, 412, 280);

    // Init scr->hotlcd_logo
    scr->hotlcd_logo = lv_img_create(scr->obj);
    lv_img_set_src(scr->hotlcd_logo, LVGL_IMAGE_PATH(about/logo_white_1024x200.png));
    lv_img_set_pivot(scr->hotlcd_logo, 50, 50);
    lv_img_set_offset_x(scr->hotlcd_logo, 0);
    lv_img_set_offset_y(scr->hotlcd_logo, 0);
    lv_img_set_angle(scr->hotlcd_logo, 0);
    lv_obj_set_pos(scr->hotlcd_logo, 0, 5);

    // Init scr->back
    scr->back = lv_img_create(scr->obj);
    lv_img_set_src(scr->back, LVGL_IMAGE_PATH(home/back_solid_80x80.png));
    lv_img_set_pivot(scr->back, 50, 50);
    lv_img_set_offset_x(scr->back, 0);
    lv_img_set_offset_y(scr->back, 0);
    lv_img_set_angle(scr->back, 0);
    lv_obj_set_pos(scr->back, 0, 520);
    lv_obj_add_flag(scr->back, LV_OBJ_FLAG_CLICKABLE);

    // Set event handler of scr->back
    lv_obj_add_event_cb(scr->back, scr_about_back_clicked, LV_EVENT_CLICKED, NULL);


}


