/*
 * Copyright (C) 2025 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.1
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"

#include "lv_aic_player.h"

static void scr_photo_container_gesture (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // delete child obj of act_scr
        lv_obj_clean(act_scr);
        // create scr_home
        scr_home_create(&ui_manager);
        // load scr_home
        lv_scr_load_anim(scr_home_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_NONE, 0, 0, ui_manager.auto_del);
    }
}

static void scr_photo_back_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // delete child obj of act_scr
        lv_obj_clean(act_scr);
        // create scr_home
        scr_home_create(&ui_manager);
        // load scr_home
        lv_scr_load_anim(scr_home_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_NONE, 0, 0, ui_manager.auto_del);
    }
}


void scr_photo_create(ui_manager_t *ui)
{
    scr_photo_t *scr = scr_photo_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xfcfcfc), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->container
    scr->container = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->container, 0, 0);
    lv_obj_set_size(scr->container, 1024, 600);
    lv_obj_set_scrollbar_mode(scr->container, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->container
    lv_obj_set_style_bg_color(scr->container, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->container, LVGL_IMAGE_PATH(photo/img1.jpg), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->container
    lv_obj_add_event_cb(scr->container, scr_photo_container_gesture, LV_EVENT_GESTURE, NULL);

    // Init scr->back
    scr->back = lv_img_create(scr->container);
    lv_img_set_src(scr->back, LVGL_IMAGE_PATH(home/back_solid_60x60.png));
    lv_img_set_pivot(scr->back, 50, 50);
    lv_img_set_angle(scr->back, 0);
    lv_obj_set_style_img_opa(scr->back, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->back, 0, 0);
    lv_obj_add_flag(scr->back, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->back
    lv_obj_set_style_img_recolor(scr->back, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(scr->back, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->back
    lv_obj_add_event_cb(scr->back, scr_photo_back_clicked, LV_EVENT_CLICKED, NULL);


}


