/*
 * Copyright (C) 2025 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.1
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"

#include "lv_aic_player.h"

void __attribute__((weak)) scr_dashboard_custom_load_start(void) {
}
void __attribute__((weak)) scr_dashboard_custom_unload_start(void) {
}

static void scr_dashboard_unload_start (lv_event_t *e) {
    scr_dashboard_custom_unload_start();
}

static void scr_dashboard_load_start (lv_event_t *e) {
    scr_dashboard_custom_load_start();
}

static void scr_dashboard_back_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // delete child obj of act_scr
        lv_obj_clean(act_scr);
        // create scr_home
        scr_home_create(&ui_manager);
        // load scr_home
        lv_scr_load_anim(scr_home_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_NONE, 0, 0, ui_manager.auto_del);
    }
}

void __attribute__((weak)) scr_dashboard_mode_custom_value_changed(void) {
}

static void scr_dashboard_mode_value_changed (lv_event_t *e) {
    scr_dashboard_mode_custom_value_changed();
}


void scr_dashboard_create(ui_manager_t *ui)
{
    scr_dashboard_t *scr = scr_dashboard_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->obj
    lv_obj_add_event_cb(scr->obj, scr_dashboard_unload_start, LV_EVENT_SCREEN_UNLOAD_START, NULL);
    lv_obj_add_event_cb(scr->obj, scr_dashboard_load_start, LV_EVENT_SCREEN_LOAD_START, NULL);

    // Init scr->bg
    scr->bg = lv_img_create(scr->obj);
    lv_img_set_src(scr->bg, LVGL_IMAGE_PATH(dashboard/bg/normal_q95.jpg));
    lv_img_set_pivot(scr->bg, 50, 50);
    lv_img_set_angle(scr->bg, 0);
    lv_obj_set_style_img_opa(scr->bg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->bg, 242, 30);

    // Init scr->back
    scr->back = lv_img_create(scr->obj);
    lv_img_set_src(scr->back, LVGL_IMAGE_PATH(home/back_solid_60x60.png));
    lv_img_set_pivot(scr->back, 50, 50);
    lv_img_set_angle(scr->back, 0);
    lv_obj_set_style_img_opa(scr->back, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->back, 0, 0);
    lv_obj_add_flag(scr->back, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->back
    lv_obj_set_style_img_recolor(scr->back, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(scr->back, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->back
    lv_obj_add_event_cb(scr->back, scr_dashboard_back_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->arc
    scr->arc = lv_arc_create(scr->obj);
    lv_arc_set_mode(scr->arc, LV_ARC_MODE_NORMAL);
    lv_arc_set_range(scr->arc, 0, 100);
    lv_arc_set_bg_angles(scr->arc, 135, 45);
    lv_arc_set_angles(scr->arc, 135, 270);
    lv_arc_set_rotation(scr->arc, 0);
    lv_obj_set_pos(scr->arc, 242, 30);
    lv_obj_set_size(scr->arc, 540, 540);

    // Init scr->speed_high
    scr->speed_high = lv_img_create(scr->obj);
    lv_img_set_src(scr->speed_high, LVGL_IMAGE_PATH(dashboard/speed_num/s_0.png));
    lv_img_set_pivot(scr->speed_high, 50, 50);
    lv_img_set_angle(scr->speed_high, 0);
    lv_obj_set_style_img_opa(scr->speed_high, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->speed_high, 450, 280);

    // Init scr->speed_low
    scr->speed_low = lv_img_create(scr->obj);
    lv_img_set_src(scr->speed_low, LVGL_IMAGE_PATH(dashboard/speed_num/s_0.png));
    lv_img_set_pivot(scr->speed_low, 50, 50);
    lv_img_set_angle(scr->speed_low, 0);
    lv_obj_set_style_img_opa(scr->speed_low, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->speed_low, 520, 280);

    // Init scr->speed_kmh
    scr->speed_kmh = lv_img_create(scr->obj);
    lv_img_set_src(scr->speed_kmh, LVGL_IMAGE_PATH(dashboard/speed_num/s_kmh.png));
    lv_img_set_pivot(scr->speed_kmh, 50, 50);
    lv_img_set_angle(scr->speed_kmh, 0);
    lv_obj_set_style_img_opa(scr->speed_kmh, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->speed_kmh, 470, 370);

    // Init scr->t12
    scr->t12 = lv_img_create(scr->obj);
    lv_img_set_src(scr->t12, LVGL_IMAGE_PATH(dashboard/head/t_12.png));
    lv_img_set_pivot(scr->t12, 50, 50);
    lv_img_set_angle(scr->t12, 0);
    lv_obj_set_style_img_opa(scr->t12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->t12, 414, 8);

    // Init scr->t7
    scr->t7 = lv_img_create(scr->obj);
    lv_img_set_src(scr->t7, LVGL_IMAGE_PATH(dashboard/head/t_7.png));
    lv_img_set_pivot(scr->t7, 50, 50);
    lv_img_set_angle(scr->t7, 0);
    lv_obj_set_style_img_opa(scr->t7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->t7, 875, 8);

    // Set style of scr->t7
    lv_obj_set_style_img_recolor(scr->t7, lv_color_hex(0x00aaff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(scr->t7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->t6
    scr->t6 = lv_img_create(scr->obj);
    lv_img_set_src(scr->t6, LVGL_IMAGE_PATH(dashboard/head/t_6.png));
    lv_img_set_pivot(scr->t6, 50, 50);
    lv_img_set_angle(scr->t6, 0);
    lv_obj_set_style_img_opa(scr->t6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->t6, 822, 8);

    // Init scr->t5
    scr->t5 = lv_img_create(scr->obj);
    lv_img_set_src(scr->t5, LVGL_IMAGE_PATH(dashboard/head/t_5.png));
    lv_img_set_pivot(scr->t5, 50, 50);
    lv_img_set_angle(scr->t5, 0);
    lv_obj_set_style_img_opa(scr->t5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->t5, 770, 8);

    // Init scr->t4
    scr->t4 = lv_img_create(scr->obj);
    lv_img_set_src(scr->t4, LVGL_IMAGE_PATH(dashboard/head/t_4.png));
    lv_img_set_pivot(scr->t4, 50, 50);
    lv_img_set_angle(scr->t4, 0);
    lv_obj_set_style_img_opa(scr->t4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->t4, 220, 8);

    // Init scr->t3
    scr->t3 = lv_img_create(scr->obj);
    lv_img_set_src(scr->t3, LVGL_IMAGE_PATH(dashboard/head/t_3.png));
    lv_img_set_pivot(scr->t3, 50, 50);
    lv_img_set_angle(scr->t3, 0);
    lv_obj_set_style_img_opa(scr->t3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->t3, 160, 8);

    // Init scr->t2
    scr->t2 = lv_img_create(scr->obj);
    lv_img_set_src(scr->t2, LVGL_IMAGE_PATH(dashboard/head/t_2.png));
    lv_img_set_pivot(scr->t2, 50, 50);
    lv_img_set_angle(scr->t2, 0);
    lv_obj_set_style_img_opa(scr->t2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->t2, 66, 100);

    // Init scr->t1
    scr->t1 = lv_img_create(scr->obj);
    lv_img_set_src(scr->t1, LVGL_IMAGE_PATH(dashboard/head/t_1.png));
    lv_img_set_pivot(scr->t1, 50, 50);
    lv_img_set_angle(scr->t1, 0);
    lv_obj_set_style_img_opa(scr->t1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->t1, 16, 100);

    // Init scr->t8
    scr->t8 = lv_img_create(scr->obj);
    lv_img_set_src(scr->t8, LVGL_IMAGE_PATH(dashboard/head/t_8.png));
    lv_img_set_pivot(scr->t8, 50, 50);
    lv_img_set_angle(scr->t8, 0);
    lv_obj_set_style_img_opa(scr->t8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->t8, 920, 8);

    // Init scr->b1
    scr->b1 = lv_img_create(scr->obj);
    lv_img_set_src(scr->b1, LVGL_IMAGE_PATH(dashboard/end/b_1.png));
    lv_img_set_pivot(scr->b1, 50, 50);
    lv_img_set_angle(scr->b1, 0);
    lv_obj_set_style_img_opa(scr->b1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->b1, 82, 528);

    // Init scr->b2
    scr->b2 = lv_img_create(scr->obj);
    lv_img_set_src(scr->b2, LVGL_IMAGE_PATH(dashboard/end/b_2.png));
    lv_img_set_pivot(scr->b2, 50, 50);
    lv_img_set_angle(scr->b2, 0);
    lv_obj_set_style_img_opa(scr->b2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->b2, 140, 528);

    // Init scr->b3
    scr->b3 = lv_img_create(scr->obj);
    lv_img_set_src(scr->b3, LVGL_IMAGE_PATH(dashboard/end/b_3.png));
    lv_img_set_pivot(scr->b3, 50, 50);
    lv_img_set_angle(scr->b3, 0);
    lv_obj_set_style_img_opa(scr->b3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->b3, 202, 528);

    // Init scr->b4
    scr->b4 = lv_img_create(scr->obj);
    lv_img_set_src(scr->b4, LVGL_IMAGE_PATH(dashboard/end/b_4.png));
    lv_img_set_pivot(scr->b4, 50, 50);
    lv_img_set_angle(scr->b4, 0);
    lv_obj_set_style_img_opa(scr->b4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->b4, 262, 528);

    // Init scr->b5
    scr->b5 = lv_img_create(scr->obj);
    lv_img_set_src(scr->b5, LVGL_IMAGE_PATH(dashboard/end/b_5.png));
    lv_img_set_pivot(scr->b5, 50, 50);
    lv_img_set_angle(scr->b5, 0);
    lv_obj_set_style_img_opa(scr->b5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->b5, 322, 528);

    // Init scr->b6
    scr->b6 = lv_img_create(scr->obj);
    lv_img_set_src(scr->b6, LVGL_IMAGE_PATH(dashboard/end/b_6.png));
    lv_img_set_pivot(scr->b6, 50, 50);
    lv_img_set_angle(scr->b6, 0);
    lv_obj_set_style_img_opa(scr->b6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->b6, 656, 528);

    // Init scr->b7
    scr->b7 = lv_img_create(scr->obj);
    lv_img_set_src(scr->b7, LVGL_IMAGE_PATH(dashboard/end/b_7.png));
    lv_img_set_pivot(scr->b7, 50, 50);
    lv_img_set_angle(scr->b7, 0);
    lv_obj_set_style_img_opa(scr->b7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->b7, 720, 528);

    // Init scr->b8
    scr->b8 = lv_img_create(scr->obj);
    lv_img_set_src(scr->b8, LVGL_IMAGE_PATH(dashboard/end/b_8.png));
    lv_img_set_pivot(scr->b8, 50, 50);
    lv_img_set_angle(scr->b8, 0);
    lv_obj_set_style_img_opa(scr->b8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->b8, 782, 528);

    // Init scr->b9
    scr->b9 = lv_img_create(scr->obj);
    lv_img_set_src(scr->b9, LVGL_IMAGE_PATH(dashboard/end/b_9.png));
    lv_img_set_pivot(scr->b9, 50, 50);
    lv_img_set_angle(scr->b9, 0);
    lv_obj_set_style_img_opa(scr->b9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->b9, 842, 534);

    // Init scr->trip
    scr->trip = lv_img_create(scr->obj);
    lv_img_set_src(scr->trip, LVGL_IMAGE_PATH(dashboard/mileage/trip.png));
    lv_img_set_pivot(scr->trip, 50, 50);
    lv_img_set_angle(scr->trip, 0);
    lv_obj_set_style_img_opa(scr->trip, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->trip, 429, 534);

    // Init scr->trip_0
    scr->trip_0 = lv_img_create(scr->obj);
    lv_img_set_src(scr->trip_0, LVGL_IMAGE_PATH(dashboard/mileage/0.png));
    lv_img_set_pivot(scr->trip_0, 50, 50);
    lv_img_set_angle(scr->trip_0, 0);
    lv_obj_set_style_img_opa(scr->trip_0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->trip_0, 495, 534);

    // Init scr->trip_1
    scr->trip_1 = lv_img_create(scr->obj);
    lv_img_set_src(scr->trip_1, LVGL_IMAGE_PATH(dashboard/mileage/0.png));
    lv_img_set_pivot(scr->trip_1, 50, 50);
    lv_img_set_angle(scr->trip_1, 0);
    lv_obj_set_style_img_opa(scr->trip_1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->trip_1, 510, 534);

    // Init scr->trip_2
    scr->trip_2 = lv_img_create(scr->obj);
    lv_img_set_src(scr->trip_2, LVGL_IMAGE_PATH(dashboard/mileage/9.png));
    lv_img_set_pivot(scr->trip_2, 50, 50);
    lv_img_set_angle(scr->trip_2, 0);
    lv_obj_set_style_img_opa(scr->trip_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->trip_2, 525, 534);

    // Init scr->trip_3
    scr->trip_3 = lv_img_create(scr->obj);
    lv_img_set_src(scr->trip_3, LVGL_IMAGE_PATH(dashboard/mileage/8.png));
    lv_img_set_pivot(scr->trip_3, 50, 50);
    lv_img_set_angle(scr->trip_3, 0);
    lv_obj_set_style_img_opa(scr->trip_3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->trip_3, 540, 534);

    // Init scr->trip_km
    scr->trip_km = lv_img_create(scr->obj);
    lv_img_set_src(scr->trip_km, LVGL_IMAGE_PATH(dashboard/mileage/km.png));
    lv_img_set_pivot(scr->trip_km, 50, 50);
    lv_img_set_angle(scr->trip_km, 0);
    lv_obj_set_style_img_opa(scr->trip_km, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->trip_km, 560, 536);

    // Init scr->mode
    scr->mode = lv_roller_create(scr->obj);
    lv_roller_set_options(scr->mode, "normal\necho\nrain\nsport", LV_ROLLER_MODE_INFINITE);
    lv_roller_set_visible_row_count(scr->mode, 3);
    lv_obj_set_pos(scr->mode, 850, 240);
    lv_obj_set_size(scr->mode, 120, 155);

    // Set style of scr->mode
    lv_obj_set_style_bg_color(scr->mode, lv_color_hex(0x00577f), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->mode, fs_droidsansfallback_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->mode, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->mode, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(scr->mode, lv_color_hex(0x00577f), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->mode, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->mode, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(scr->mode, lv_color_hex(0x00577f), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(scr->mode, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(scr->mode, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(scr->mode, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(scr->mode, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->mode, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->mode, fs_montserratmedium_16, LV_PART_SELECTED | LV_STATE_DEFAULT);

    // Set event handler of scr->mode
    lv_obj_add_event_cb(scr->mode, scr_dashboard_mode_value_changed, LV_EVENT_VALUE_CHANGED, NULL);


}


