/*
 * Copyright (C) 2025 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.1
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"


static void scr_home_app_dashboard_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // delete child obj of act_scr
        lv_obj_clean(act_scr);
        // create scr_dashboard
        scr_dashboard_create(&ui_manager);
        // load scr_dashboard
        lv_scr_load_anim(scr_dashboard_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_NONE, 0, 0, ui_manager.auto_del);
    }
}

static void scr_home_app_video_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // delete child obj of act_scr
        lv_obj_clean(act_scr);
        // create scr_video
        scr_video_create(&ui_manager);
        // load scr_video
        lv_scr_load_anim(scr_video_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_NONE, 0, 0, ui_manager.auto_del);
    }
}

static void scr_home_app_image_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // delete child obj of act_scr
        lv_obj_clean(act_scr);
        // create scr_photo
        scr_photo_create(&ui_manager);
        // load scr_photo
        lv_scr_load_anim(scr_photo_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_NONE, 0, 0, ui_manager.auto_del);
    }
}

static void scr_home_about_us_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // delete child obj of act_scr
        lv_obj_clean(act_scr);
        // create scr_about
        scr_about_create(&ui_manager);
        // load scr_about
        lv_scr_load_anim(scr_about_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_NONE, 0, 0, ui_manager.auto_del);
    }
}


void scr_home_create(ui_manager_t *ui)
{
    scr_home_t *scr = scr_home_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xfcfcfc), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->obj, LVGL_IMAGE_PATH(home/main_bg.jpg), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->MainTile
    scr->MainTile = lv_tileview_create(scr->obj);
    lv_obj_t *scr_home_MainTile_tile_1 = lv_tileview_add_tile(scr->MainTile, 0, 0, LV_DIR_ALL);
    lv_obj_t *scr_home_MainTile_tile_2 = lv_tileview_add_tile(scr->MainTile, 1, 0, LV_DIR_ALL);
    lv_obj_set_pos(scr->MainTile, 0, 60);
    lv_obj_set_size(scr->MainTile, 1024, 480);
    lv_obj_set_scrollbar_mode(scr->MainTile, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->MainTile
    lv_obj_set_style_bg_opa(scr->MainTile, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->app_music
    scr->app_music = lv_imgbtn_create(scr_home_MainTile_tile_1);
    lv_imgbtn_set_src(scr->app_music, LV_IMGBTN_STATE_RELEASED, NULL, LVGL_IMAGE_PATH(home/music.png), NULL);
    lv_obj_t *scr_home_app_music_label = lv_label_create(scr->app_music);
    lv_label_set_text(scr_home_app_music_label, "");
    lv_obj_align(scr_home_app_music_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->app_music, 670, 100);
    lv_obj_set_size(scr->app_music, 100, 100);

    // Set style of scr->app_music
    lv_obj_set_style_text_font(scr->app_music, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->app_wifi
    scr->app_wifi = lv_imgbtn_create(scr_home_MainTile_tile_1);
    lv_imgbtn_set_src(scr->app_wifi, LV_IMGBTN_STATE_RELEASED, NULL, LVGL_IMAGE_PATH(home/internet.png), NULL);
    lv_obj_t *scr_home_app_wifi_label = lv_label_create(scr->app_wifi);
    lv_label_set_text(scr_home_app_wifi_label, "");
    lv_obj_align(scr_home_app_wifi_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->app_wifi, 470, 100);
    lv_obj_set_size(scr->app_wifi, 100, 100);

    // Set style of scr->app_wifi
    lv_obj_set_style_text_font(scr->app_wifi, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->app_dashboard
    scr->app_dashboard = lv_imgbtn_create(scr_home_MainTile_tile_1);
    lv_imgbtn_set_src(scr->app_dashboard, LV_IMGBTN_STATE_RELEASED, NULL, LVGL_IMAGE_PATH(home/dashboard.png), NULL);
    lv_obj_t *scr_home_app_dashboard_label = lv_label_create(scr->app_dashboard);
    lv_label_set_text(scr_home_app_dashboard_label, "");
    lv_obj_align(scr_home_app_dashboard_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->app_dashboard, 270, 100);
    lv_obj_set_size(scr->app_dashboard, 100, 100);

    // Set style of scr->app_dashboard
    lv_obj_set_style_text_font(scr->app_dashboard, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(scr->app_dashboard, 0, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_ofs_x(scr->app_dashboard, 2, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_ofs_y(scr->app_dashboard, 2, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(scr->app_dashboard, 2, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(scr->app_dashboard, 10, LV_PART_MAIN | LV_STATE_PRESSED);

    // Set event handler of scr->app_dashboard
    lv_obj_add_event_cb(scr->app_dashboard, scr_home_app_dashboard_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->app_cpu
    scr->app_cpu = lv_imgbtn_create(scr_home_MainTile_tile_1);
    lv_imgbtn_set_src(scr->app_cpu, LV_IMGBTN_STATE_RELEASED, NULL, LVGL_IMAGE_PATH(home/cpu.png), NULL);
    lv_obj_t *scr_home_app_cpu_label = lv_label_create(scr->app_cpu);
    lv_label_set_text(scr_home_app_cpu_label, "");
    lv_obj_align(scr_home_app_cpu_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->app_cpu, 70, 100);
    lv_obj_set_size(scr->app_cpu, 100, 100);

    // Set style of scr->app_cpu
    lv_obj_set_style_text_font(scr->app_cpu, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->app_video
    scr->app_video = lv_imgbtn_create(scr_home_MainTile_tile_1);
    lv_imgbtn_set_src(scr->app_video, LV_IMGBTN_STATE_RELEASED, NULL, LVGL_IMAGE_PATH(home/video.png), NULL);
    lv_obj_t *scr_home_app_video_label = lv_label_create(scr->app_video);
    lv_label_set_text(scr_home_app_video_label, "");
    lv_obj_align(scr_home_app_video_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->app_video, 870, 100);
    lv_obj_set_size(scr->app_video, 100, 100);

    // Set style of scr->app_video
    lv_obj_set_style_text_font(scr->app_video, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->app_video
    lv_obj_add_event_cb(scr->app_video, scr_home_app_video_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->app_web
    scr->app_web = lv_imgbtn_create(scr_home_MainTile_tile_1);
    lv_imgbtn_set_src(scr->app_web, LV_IMGBTN_STATE_RELEASED, NULL, LVGL_IMAGE_PATH(home/website.png), NULL);
    lv_obj_t *scr_home_app_web_label = lv_label_create(scr->app_web);
    lv_label_set_text(scr_home_app_web_label, "");
    lv_obj_align(scr_home_app_web_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->app_web, 70, 300);
    lv_obj_set_size(scr->app_web, 100, 100);

    // Set style of scr->app_web
    lv_obj_set_style_text_font(scr->app_web, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->app_image
    scr->app_image = lv_imgbtn_create(scr_home_MainTile_tile_1);
    lv_imgbtn_set_src(scr->app_image, LV_IMGBTN_STATE_RELEASED, NULL, LVGL_IMAGE_PATH(home/picture.png), NULL);
    lv_obj_t *scr_home_app_image_label = lv_label_create(scr->app_image);
    lv_label_set_text(scr_home_app_image_label, "");
    lv_obj_align(scr_home_app_image_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->app_image, 670, 300);
    lv_obj_set_size(scr->app_image, 100, 100);

    // Set style of scr->app_image
    lv_obj_set_style_text_font(scr->app_image, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->app_image
    lv_obj_add_event_cb(scr->app_image, scr_home_app_image_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->app_weather
    scr->app_weather = lv_imgbtn_create(scr_home_MainTile_tile_1);
    lv_imgbtn_set_src(scr->app_weather, LV_IMGBTN_STATE_RELEASED, NULL, LVGL_IMAGE_PATH(home/weather.png), NULL);
    lv_obj_t *scr_home_app_weather_label = lv_label_create(scr->app_weather);
    lv_label_set_text(scr_home_app_weather_label, "");
    lv_obj_align(scr_home_app_weather_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->app_weather, 270, 300);
    lv_obj_set_size(scr->app_weather, 100, 100);

    // Set style of scr->app_weather
    lv_obj_set_style_text_font(scr->app_weather, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->app_setting
    scr->app_setting = lv_imgbtn_create(scr_home_MainTile_tile_1);
    lv_imgbtn_set_src(scr->app_setting, LV_IMGBTN_STATE_RELEASED, NULL, LVGL_IMAGE_PATH(home/system.png), NULL);
    lv_obj_t *scr_home_app_setting_label = lv_label_create(scr->app_setting);
    lv_label_set_text(scr_home_app_setting_label, "");
    lv_obj_align(scr_home_app_setting_label, LV_ALIGN_LEFT_MID, 0, 0);
    lv_obj_set_pos(scr->app_setting, 870, 300);
    lv_obj_set_size(scr->app_setting, 100, 100);

    // Set style of scr->app_setting
    lv_obj_set_style_text_font(scr->app_setting, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->app_setting, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->app_canvas
    scr->app_canvas = lv_imgbtn_create(scr_home_MainTile_tile_1);
    lv_imgbtn_set_src(scr->app_canvas, LV_IMGBTN_STATE_RELEASED, NULL, LVGL_IMAGE_PATH(home/canvas.png), NULL);
    lv_obj_t *scr_home_app_canvas_label = lv_label_create(scr->app_canvas);
    lv_label_set_text(scr_home_app_canvas_label, "");
    lv_obj_align(scr_home_app_canvas_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->app_canvas, 470, 300);
    lv_obj_set_size(scr->app_canvas, 100, 100);

    // Set style of scr->app_canvas
    lv_obj_set_style_text_font(scr->app_canvas, fs_droidsansfallback_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->about_us
    scr->about_us = lv_imgbtn_create(scr_home_MainTile_tile_2);
    lv_imgbtn_set_src(scr->about_us, LV_IMGBTN_STATE_RELEASED, NULL, LVGL_IMAGE_PATH(home/about_100x100.png), NULL);
    lv_obj_t *scr_home_about_us_label = lv_label_create(scr->about_us);
    lv_label_set_text(scr_home_about_us_label, "");
    lv_obj_align(scr_home_about_us_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->about_us, 70, 100);
    lv_obj_set_size(scr->about_us, 100, 100);

    // Set style of scr->about_us
    lv_obj_set_style_text_font(scr->about_us, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->about_us
    lv_obj_add_event_cb(scr->about_us, scr_home_about_us_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->status_container
    scr->status_container = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->status_container, 0, 0);
    lv_obj_set_size(scr->status_container, 1024, 50);
    lv_obj_set_scrollbar_mode(scr->status_container, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->status_container
    lv_obj_set_style_bg_color(scr->status_container, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->status_container, 44, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->status_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->status_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->status_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->status_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->status_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->status_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->date_label
    scr->date_label = lv_label_create(scr->status_container);
    lv_label_set_text(scr->date_label, "2025/12/18");
    lv_label_set_long_mode(scr->date_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->date_label, 780, 15);
    lv_obj_set_size(scr->date_label, 100, 20);

    // Set style of scr->date_label
    lv_obj_set_style_text_font(scr->date_label, fs_montserratmedium_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->date_label, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->time_label
    scr->time_label = lv_label_create(scr->status_container);
    lv_label_set_text(scr->time_label, "20:29:00");
    lv_label_set_long_mode(scr->time_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->time_label, 924, 15);
    lv_obj_set_size(scr->time_label, 100, 20);

    // Set style of scr->time_label
    lv_obj_set_style_text_font(scr->time_label, fs_montserratmedium_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->time_label, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->wifi
    scr->wifi = lv_img_create(scr->status_container);
    lv_img_set_src(scr->wifi, LVGL_IMAGE_PATH(home/wifi_dis_40x40.png));
    lv_img_set_pivot(scr->wifi, 50, 50);
    lv_img_set_angle(scr->wifi, 0);
    lv_obj_set_style_img_opa(scr->wifi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->wifi, 80, 5);

    // Init scr->battery
    scr->battery = lv_img_create(scr->status_container);
    lv_img_set_src(scr->battery, LVGL_IMAGE_PATH(home/battery-full_40x40.png));
    lv_img_set_pivot(scr->battery, 50, 50);
    lv_img_set_angle(scr->battery, 0);
    lv_obj_set_style_img_opa(scr->battery, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->battery, 20, 5);

    // Init scr->bluetooth
    scr->bluetooth = lv_img_create(scr->status_container);
    lv_img_set_src(scr->bluetooth, LVGL_IMAGE_PATH(home/bluetooth_dis_40x40.png));
    lv_img_set_pivot(scr->bluetooth, 50, 50);
    lv_img_set_angle(scr->bluetooth, 0);
    lv_obj_set_style_img_opa(scr->bluetooth, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->bluetooth, 140, 5);

    // Init scr->sdcard
    scr->sdcard = lv_img_create(scr->status_container);
    lv_img_set_src(scr->sdcard, LVGL_IMAGE_PATH(home/sdcard_40x40.png));
    lv_img_set_pivot(scr->sdcard, 50, 50);
    lv_img_set_angle(scr->sdcard, 0);
    lv_obj_set_style_img_opa(scr->sdcard, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->sdcard, 200, 5);

    // Init scr->udsik
    scr->udsik = lv_img_create(scr->status_container);
    lv_img_set_src(scr->udsik, LVGL_IMAGE_PATH(home/udisk_40x40.png));
    lv_img_set_pivot(scr->udsik, 50, 50);
    lv_img_set_angle(scr->udsik, 0);
    lv_obj_set_style_img_opa(scr->udsik, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->udsik, 260, 5);


}


