/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by UIBuilder
 * UIBuilder version: v2.1.1
 */

#include "ui_init.h"
#include "ui_util.h"
#include "aic_ui.h"
#include "custom/custom.h"

ui_manager_t ui_manager;

lv_font_t *fs_montserratmedium_16;
lv_font_t *fs_droidsansfallback_16;
lv_font_t *fs_montserratmedium_18;
lv_font_t *fs_montserratmedium_30;
lv_font_t *fs_droidsansfallback_24;

void ui_init(void)
{
    fs_montserratmedium_16 = ui_font_init(LVGL_FONT_PATH(montserratMedium.ttf), 16);
    fs_droidsansfallback_16 = ui_font_init(LVGL_FONT_PATH(DroidSansFallback.ttf), 16);
    fs_montserratmedium_18 = ui_font_init(LVGL_FONT_PATH(montserratMedium.ttf), 18);
    fs_montserratmedium_30 = ui_font_init(LVGL_FONT_PATH(montserratMedium.ttf), 30);
    fs_droidsansfallback_24 = ui_font_init(LVGL_FONT_PATH(DroidSansFallback.ttf), 24);
    if (!fs_montserratmedium_16) {
    	LV_LOG_ERROR("Failed to init fs_montserratmedium_16");
    	return;
    }
    if (!fs_droidsansfallback_16) {
    	LV_LOG_ERROR("Failed to init fs_droidsansfallback_16");
    	return;
    }
    if (!fs_montserratmedium_18) {
    	LV_LOG_ERROR("Failed to init fs_montserratmedium_18");
    	return;
    }
    if (!fs_montserratmedium_30) {
    	LV_LOG_ERROR("Failed to init fs_montserratmedium_30");
    	return;
    }
    if (!fs_droidsansfallback_24) {
    	LV_LOG_ERROR("Failed to init fs_droidsansfallback_24");
    	return;
    }

    // auto delete screen
    ui_manager_init(&ui_manager, true);

    scr_home_create(&ui_manager);
    lv_scr_load(scr_home_get(&ui_manager)->obj);

    // custom code
    custom_init();
}
