/*
 * Copyright (C) 2025 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.1
 */

#ifndef _UI_OBJECTS
#define _UI_OBJECTS

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"
#include "lv_conf_custom.h"


typedef struct {
    lv_obj_t *obj;
    lv_obj_t *MainTile;
    lv_obj_t *app_music;
    lv_obj_t *app_wifi;
    lv_obj_t *app_dashboard;
    lv_obj_t *app_cpu;
    lv_obj_t *app_video;
    lv_obj_t *app_web;
    lv_obj_t *app_image;
    lv_obj_t *app_weather;
    lv_obj_t *app_setting;
    lv_obj_t *app_canvas;
    lv_obj_t *about_us;
    lv_obj_t *status_container;
    lv_obj_t *date_label;
    lv_obj_t *time_label;
    lv_obj_t *wifi;
    lv_obj_t *battery;
    lv_obj_t *bluetooth;
    lv_obj_t *sdcard;
    lv_obj_t *udsik;
} scr_home_t;

typedef struct {
    lv_obj_t *obj;
    lv_obj_t *video_player;
    lv_obj_t *control_bar;
    lv_obj_t *next;
    lv_obj_t *last;
    lv_obj_t *zoom;
    lv_obj_t *play_control;
    lv_obj_t *author;
    lv_obj_t *file_name;
    lv_obj_t *back;
} scr_video_t;

typedef struct {
    lv_obj_t *obj;
    lv_obj_t *qrcode_1;
    lv_obj_t *hotlcd_logo;
    lv_obj_t *back;
} scr_about_t;

typedef struct {
    lv_obj_t *obj;
    lv_obj_t *bg;
    lv_obj_t *back;
    lv_obj_t *arc;
    lv_obj_t *speed_high;
    lv_obj_t *speed_low;
    lv_obj_t *speed_kmh;
    lv_obj_t *t12;
    lv_obj_t *t7;
    lv_obj_t *t6;
    lv_obj_t *t5;
    lv_obj_t *t4;
    lv_obj_t *t3;
    lv_obj_t *t2;
    lv_obj_t *t1;
    lv_obj_t *t8;
    lv_obj_t *b1;
    lv_obj_t *b2;
    lv_obj_t *b3;
    lv_obj_t *b4;
    lv_obj_t *b5;
    lv_obj_t *b6;
    lv_obj_t *b7;
    lv_obj_t *b8;
    lv_obj_t *b9;
    lv_obj_t *trip;
    lv_obj_t *trip_0;
    lv_obj_t *trip_1;
    lv_obj_t *trip_2;
    lv_obj_t *trip_3;
    lv_obj_t *trip_km;
    lv_obj_t *mode;
} scr_dashboard_t;

typedef struct {
    lv_obj_t *obj;
    lv_obj_t *container_2;
} scr_wifi_t;

typedef struct {
    lv_obj_t *obj;
    lv_obj_t *container;
    lv_obj_t *menu;
    lv_obj_t *container_1;
} scr_setting_t;

typedef struct {
    lv_obj_t *obj;
    lv_obj_t *container;
    lv_obj_t *back;
} scr_photo_t;


typedef struct {
    bool auto_del;
    scr_home_t scr_home;
    scr_video_t scr_video;
    scr_about_t scr_about;
    scr_dashboard_t scr_dashboard;
    scr_wifi_t scr_wifi;
    scr_setting_t scr_setting;
    scr_photo_t scr_photo;

} ui_manager_t;

static inline void ui_manager_init(ui_manager_t *ui, bool auto_del)
{
    memset(ui, 0 , sizeof(ui_manager_t));
    ui->auto_del = auto_del;
}

static inline scr_home_t *scr_home_get(ui_manager_t *ui)
{
    return &ui->scr_home;
}

static inline scr_video_t *scr_video_get(ui_manager_t *ui)
{
    return &ui->scr_video;
}

static inline scr_about_t *scr_about_get(ui_manager_t *ui)
{
    return &ui->scr_about;
}

static inline scr_dashboard_t *scr_dashboard_get(ui_manager_t *ui)
{
    return &ui->scr_dashboard;
}

static inline scr_wifi_t *scr_wifi_get(ui_manager_t *ui)
{
    return &ui->scr_wifi;
}

static inline scr_setting_t *scr_setting_get(ui_manager_t *ui)
{
    return &ui->scr_setting;
}

static inline scr_photo_t *scr_photo_get(ui_manager_t *ui)
{
    return &ui->scr_photo;
}


void scr_home_create(ui_manager_t *ui);
void scr_video_create(ui_manager_t *ui);
void scr_about_create(ui_manager_t *ui);
void scr_dashboard_create(ui_manager_t *ui);
void scr_wifi_create(ui_manager_t *ui);
void scr_setting_create(ui_manager_t *ui);
void scr_photo_create(ui_manager_t *ui);


extern lv_font_t *fs_montserratmedium_16;
extern lv_font_t *fs_droidsansfallback_16;
extern lv_font_t *fs_montserratmedium_18;
extern lv_font_t *fs_montserratmedium_30;
extern lv_font_t *fs_droidsansfallback_24;


extern ui_manager_t ui_manager;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif // _UI_OBJECTS
