Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = []
src += Glob('*.c')
CPPPATH = [cwd]

group = DefineGroup('weather', src, depend = ['LPKG_USING_WEBCLIENT'], CPPPATH = CPPPATH)

Return('group')