Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = []
src += Glob('*.c')
CPPPATH = [cwd]

group = DefineGroup('keyadc', src, depend = ['AIC_USING_GPAI'], CPPPATH = CPPPATH)

Return('group')