/*
 * Copyright (C) 2025 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.1
 */

#include "custom.h"

void custom_init() {
    player_list_init();

    if (player_list_get_count() < 0) {
        printf("Warning: No video files found\n");
    } else {
        player_list.current++;
        if (player_list.current >= player_list.count)
            player_list.current = 0; 
    }

}



