Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
src += Glob('uart/*.c')
src += Glob('touch/*.c')
src += Glob('cir/*.c')


CPPPATH = [cwd, ]
CPPPATH.append(cwd + '.')
CPPPATH.append(cwd + 'uart/.')

CFLAGS = ' -c -ffunction-sections'

group  = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH, CFLAGS=CFLAGS)

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
