Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = []
src += Glob('*.c')
CPPPATH = [cwd]

group = DefineGroup('draw', src, depend = ['APP_USE_DRAW_LINE_TEST'], CPPPATH = CPPPATH)

Return('group')